name: viber_bot
description: Library to implement a Viber Rest Api.
version: 0.1.0

authors:
- Ilya Drats <idrats@yandex.ru>

homepage: https://github.com/idrats/dart-viber-bot
documentation:

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  http: ^0.11.3
